services:
  - type: web
    name: file-protector-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: file_backups
      - key: PORT
        value: 10000
    healthCheckPath: /api/status

